{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace (default $.Values.namespace.name .namespace) }}
{{- if .data }}
data:
{{ .data | toYaml | indent 2 }}
{{- end }}
{{- if .stringData }}
stringData:
{{ .stringData | toYaml | indent 2}}
{{- end }}
{{- end }}