name: Build and deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/__IMAGE_REPO_NAME__/__IMAGE_NAME__:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/__IMAGE_REPO_NAME__/__IMAGE_NAME__:${GITHUB_SHA}

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v3
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with: 
          exec: helm upgrade __HELM_RELEASE_NAME__ . --install --namespace=__NAMESPACE__NAME__ --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
